[versions]
tg-bot = "9.1.1"
ksp = "2.3.5"

kotlin = "2.3.0"

[libraries]
ktor-starter = { module = "eu.vendeli:ktor-starter", version.ref = "tg-bot" }

[plugins]
telegram-bot = { id = "eu.vendeli.telegram-bot", version.ref = "tg-bot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }